### ISSUE TITLE
Both Client and Server Broken

### ISSUE THREAD

**Issue by i-Ac1D-i** [Unnamed-Studios-LLC/Trials-Of-Titan#1]
I can't seem to be able to compile both client and server. I supplied all the libraries and dependancies and such but the code itself has way too many errors :c I just want to be able to host the server locally and try the game on my machine

**Comment by Juiix** [comment]
Unfortunately, this project is not a high enough priority for me atm to find time to fix it publicly. The source will stay as-is for now.

**Comment by Juiix** [comment]
> I can't seem to be able to compile both client and server. I supplied all the libraries and dependancies and such but the code itself has way too many errors :c I just want to be able to host the server locally and try the game on my machine

The source has now been fixed
